name: bookeat
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.5'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  provider: ^6.0.5
  firebase_crashlytics: ^3.1.0
  cloud_firestore: ^4.5.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.0-nullsafety.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/BookEat_2.png
    - lib/assets/authBgImage.png
    - lib/assets/authenticationWeb.png
    - lib/assets/bar1.jpg
    - lib/assets/bar2.jpg
    - lib/assets/bar3.jpg
    - lib/assets/bar4.jpg
    - lib/assets/bar5.jpg
    - lib/assets/cafe.jpeg
    - lib/assets/cafegourmand.jpg
    - lib/assets/dessert1.png
    - lib/assets/dessert2.jpg
    - lib/assets/dessert3.jpeg
    - lib/assets/dessert4.jpg
    - lib/assets/dessert5.jpg
    - lib/assets/dessert6.jpg
    - lib/assets/entree1.jpg
    - lib/assets/entree2.jpg
    - lib/assets/entree3.jpg
    - lib/assets/entree4.jpg
    - lib/assets/entree5.png
    - lib/assets/entree6.jpg
    - lib/assets/plat1.jpg
    - lib/assets/plat2.jpg
    - lib/assets/plat3.jpeg
    - lib/assets/plat4.jpg
    - lib/assets/plat5.jpg
    - lib/assets/plat6.jpg
    - lib/assets/plat7.jpg
    - lib/assets/restaurant1.png
    - lib/assets/restaurant2.jpg
    - lib/assets/restaurant3.jpg
    - lib/assets/restaurant4.jpg
    - lib/assets/restaurant5.jpg
    - lib/assets/restaurant6.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
